package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Attedence generated by hbm2java
 */
public class Attedence  implements java.io.Serializable {


     private Integer idattedence;
     private Employee employee;
     private Date indate;
     private Date outdate;
     private Integer type;
     private Integer status;

    public Attedence() {
    }

	
    public Attedence(Employee employee) {
        this.employee = employee;
    }
    public Attedence(Employee employee, Date indate, Date outdate, Integer type, Integer status) {
       this.employee = employee;
       this.indate = indate;
       this.outdate = outdate;
       this.type = type;
       this.status = status;
    }
   
    public Integer getIdattedence() {
        return this.idattedence;
    }
    
    public void setIdattedence(Integer idattedence) {
        this.idattedence = idattedence;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getIndate() {
        return this.indate;
    }
    
    public void setIndate(Date indate) {
        this.indate = indate;
    }
    public Date getOutdate() {
        return this.outdate;
    }
    
    public void setOutdate(Date outdate) {
        this.outdate = outdate;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


