package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer idbrand;
     private String name;
     private Set rawItems = new HashSet(0);

    public Brand() {
    }

    public Brand(String name, Set rawItems) {
       this.name = name;
       this.rawItems = rawItems;
    }
   
    public Integer getIdbrand() {
        return this.idbrand;
    }
    
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(Set rawItems) {
        this.rawItems = rawItems;
    }




}


