package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idcustomer;
     private String firstName;
     private String lastName;
     private String contact;
     private String description;
     private Set orders = new HashSet(0);
     private Set plates = new HashSet(0);

    public Customer() {
    }

    public Customer(String firstName, String lastName, String contact, String description, Set orders, Set plates) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.contact = contact;
       this.description = description;
       this.orders = orders;
       this.plates = plates;
    }
   
    public Integer getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getPlates() {
        return this.plates;
    }
    
    public void setPlates(Set plates) {
        this.plates = plates;
    }




}


