package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddeliveryNote;
     private Date date;
     private String description;
     private Set orderItemHasDeliveries = new HashSet(0);

    public Delivery() {
    }

    public Delivery(Date date, String description, Set orderItemHasDeliveries) {
       this.date = date;
       this.description = description;
       this.orderItemHasDeliveries = orderItemHasDeliveries;
    }
   
    public Integer getIddeliveryNote() {
        return this.iddeliveryNote;
    }
    
    public void setIddeliveryNote(Integer iddeliveryNote) {
        this.iddeliveryNote = iddeliveryNote;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrderItemHasDeliveries() {
        return this.orderItemHasDeliveries;
    }
    
    public void setOrderItemHasDeliveries(Set orderItemHasDeliveries) {
        this.orderItemHasDeliveries = orderItemHasDeliveries;
    }




}


