package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryStatus generated by hbm2java
 */
public class DeliveryStatus  implements java.io.Serializable {


     private Integer iddeliveryStatus;
     private String status;
     private Integer code;
     private Set deliveries = new HashSet(0);

    public DeliveryStatus() {
    }

    public DeliveryStatus(String status, Integer code, Set deliveries) {
       this.status = status;
       this.code = code;
       this.deliveries = deliveries;
    }
   
    public Integer getIddeliveryStatus() {
        return this.iddeliveryStatus;
    }
    
    public void setIddeliveryStatus(Integer iddeliveryStatus) {
        this.iddeliveryStatus = iddeliveryStatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }




}


