package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddeliveryNote;
     private DeliveryStatus deliveryStatus;
     private Order order;
     private Date date;
     private String description;
     private Set orderItemHasDeliveries = new HashSet(0);

    public Delivery() {
    }

	
    public Delivery(DeliveryStatus deliveryStatus, Order order) {
        this.deliveryStatus = deliveryStatus;
        this.order = order;
    }
    public Delivery(DeliveryStatus deliveryStatus, Order order, Date date, String description, Set orderItemHasDeliveries) {
       this.deliveryStatus = deliveryStatus;
       this.order = order;
       this.date = date;
       this.description = description;
       this.orderItemHasDeliveries = orderItemHasDeliveries;
    }
   
    public Integer getIddeliveryNote() {
        return this.iddeliveryNote;
    }
    
    public void setIddeliveryNote(Integer iddeliveryNote) {
        this.iddeliveryNote = iddeliveryNote;
    }
    public DeliveryStatus getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(DeliveryStatus deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrderItemHasDeliveries() {
        return this.orderItemHasDeliveries;
    }
    
    public void setOrderItemHasDeliveries(Set orderItemHasDeliveries) {
        this.orderItemHasDeliveries = orderItemHasDeliveries;
    }




}


