package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer idemployee;
     private EmployeeAddress employeeAddress;
     private String nic;
     private String name;
     private String contact;
     private String photo;
     private String employeeStatus;
     private Integer type;
     private String email;
     private Set attedences = new HashSet(0);
     private Set users = new HashSet(0);

    public Employee() {
    }

	
    public Employee(EmployeeAddress employeeAddress) {
        this.employeeAddress = employeeAddress;
    }
    public Employee(EmployeeAddress employeeAddress, String nic, String name, String contact, String photo, String employeeStatus, Integer type, String email, Set attedences, Set users) {
       this.employeeAddress = employeeAddress;
       this.nic = nic;
       this.name = name;
       this.contact = contact;
       this.photo = photo;
       this.employeeStatus = employeeStatus;
       this.type = type;
       this.email = email;
       this.attedences = attedences;
       this.users = users;
    }
   
    public Integer getIdemployee() {
        return this.idemployee;
    }
    
    public void setIdemployee(Integer idemployee) {
        this.idemployee = idemployee;
    }
    public EmployeeAddress getEmployeeAddress() {
        return this.employeeAddress;
    }
    
    public void setEmployeeAddress(EmployeeAddress employeeAddress) {
        this.employeeAddress = employeeAddress;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getEmployeeStatus() {
        return this.employeeStatus;
    }
    
    public void setEmployeeStatus(String employeeStatus) {
        this.employeeStatus = employeeStatus;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getAttedences() {
        return this.attedences;
    }
    
    public void setAttedences(Set attedences) {
        this.attedences = attedences;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


