package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeAddress generated by hbm2java
 */
public class EmployeeAddress  implements java.io.Serializable {


     private Integer idemployeeAddress;
     private String no;
     private String street1;
     private String street2;
     private String city;
     private Set employees = new HashSet(0);

    public EmployeeAddress() {
    }

    public EmployeeAddress(String no, String street1, String street2, String city, Set employees) {
       this.no = no;
       this.street1 = street1;
       this.street2 = street2;
       this.city = city;
       this.employees = employees;
    }
   
    public Integer getIdemployeeAddress() {
        return this.idemployeeAddress;
    }
    
    public void setIdemployeeAddress(Integer idemployeeAddress) {
        this.idemployeeAddress = idemployeeAddress;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


