package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer idgrn;
     private Supplier supplier;
     private Double total;
     private Double subTotal;
     private Date date;
     private Set grnItems = new HashSet(0);
     private Set stocks = new HashSet(0);

    public Grn() {
    }

	
    public Grn(Supplier supplier) {
        this.supplier = supplier;
    }
    public Grn(Supplier supplier, Double total, Double subTotal, Date date, Set grnItems, Set stocks) {
       this.supplier = supplier;
       this.total = total;
       this.subTotal = subTotal;
       this.date = date;
       this.grnItems = grnItems;
       this.stocks = stocks;
    }
   
    public Integer getIdgrn() {
        return this.idgrn;
    }
    
    public void setIdgrn(Integer idgrn) {
        this.idgrn = idgrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


