package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1



/**
 * GrnItem generated by hbm2java
 */
public class GrnItem  implements java.io.Serializable {


     private Integer idgrnItem;
     private Grn grn;
     private RawItem rawItem;
     private double unitPrice;
     private int qty;
     private double subTotal;

    public GrnItem() {
    }

    public GrnItem(Grn grn, RawItem rawItem, double unitPrice, int qty, double subTotal) {
       this.grn = grn;
       this.rawItem = rawItem;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.subTotal = subTotal;
    }
   
    public Integer getIdgrnItem() {
        return this.idgrnItem;
    }
    
    public void setIdgrnItem(Integer idgrnItem) {
        this.idgrnItem = idgrnItem;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public RawItem getRawItem() {
        return this.rawItem;
    }
    
    public void setRawItem(RawItem rawItem) {
        this.rawItem = rawItem;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }




}


