package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private Order order;
     private Date date;
     private Double paymentValue;

    public Invoice() {
    }

	
    public Invoice(Order order) {
        this.order = order;
    }
    public Invoice(Order order, Date date, Double paymentValue) {
       this.order = order;
       this.date = date;
       this.paymentValue = paymentValue;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getPaymentValue() {
        return this.paymentValue;
    }
    
    public void setPaymentValue(Double paymentValue) {
        this.paymentValue = paymentValue;
    }




}


