package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Machine generated by hbm2java
 */
public class Machine  implements java.io.Serializable {


     private Integer idmachine;
     private MachineStatus machineStatus;
     private String name;
     private Set printingJobs = new HashSet(0);

    public Machine() {
    }

	
    public Machine(MachineStatus machineStatus) {
        this.machineStatus = machineStatus;
    }
    public Machine(MachineStatus machineStatus, String name, Set printingJobs) {
       this.machineStatus = machineStatus;
       this.name = name;
       this.printingJobs = printingJobs;
    }
   
    public Integer getIdmachine() {
        return this.idmachine;
    }
    
    public void setIdmachine(Integer idmachine) {
        this.idmachine = idmachine;
    }
    public MachineStatus getMachineStatus() {
        return this.machineStatus;
    }
    
    public void setMachineStatus(MachineStatus machineStatus) {
        this.machineStatus = machineStatus;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPrintingJobs() {
        return this.printingJobs;
    }
    
    public void setPrintingJobs(Set printingJobs) {
        this.printingJobs = printingJobs;
    }




}


