package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MachineStatus generated by hbm2java
 */
public class MachineStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set machines = new HashSet(0);

    public MachineStatus() {
    }

    public MachineStatus(String status, Set machines) {
       this.status = status;
       this.machines = machines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getMachines() {
        return this.machines;
    }
    
    public void setMachines(Set machines) {
        this.machines = machines;
    }




}


