package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem  implements java.io.Serializable {


     private Integer idorderItem;
     private Order order;
     private SellingItems sellingItems;
     private Double unitPrice;
     private Integer qty;
     private String orderItemDescription;
     private Set orderItemHasDeliveries = new HashSet(0);

    public OrderItem() {
    }

	
    public OrderItem(Order order, SellingItems sellingItems) {
        this.order = order;
        this.sellingItems = sellingItems;
    }
    public OrderItem(Order order, SellingItems sellingItems, Double unitPrice, Integer qty, String orderItemDescription, Set orderItemHasDeliveries) {
       this.order = order;
       this.sellingItems = sellingItems;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.orderItemDescription = orderItemDescription;
       this.orderItemHasDeliveries = orderItemHasDeliveries;
    }
   
    public Integer getIdorderItem() {
        return this.idorderItem;
    }
    
    public void setIdorderItem(Integer idorderItem) {
        this.idorderItem = idorderItem;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public SellingItems getSellingItems() {
        return this.sellingItems;
    }
    
    public void setSellingItems(SellingItems sellingItems) {
        this.sellingItems = sellingItems;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getOrderItemDescription() {
        return this.orderItemDescription;
    }
    
    public void setOrderItemDescription(String orderItemDescription) {
        this.orderItemDescription = orderItemDescription;
    }
    public Set getOrderItemHasDeliveries() {
        return this.orderItemHasDeliveries;
    }
    
    public void setOrderItemHasDeliveries(Set orderItemHasDeliveries) {
        this.orderItemHasDeliveries = orderItemHasDeliveries;
    }




}


