package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus  implements java.io.Serializable {


     private Integer idorderStatus;
     private String status;
     private Integer code;
     private Set orders = new HashSet(0);

    public OrderStatus() {
    }

    public OrderStatus(String status, Integer code, Set orders) {
       this.status = status;
       this.code = code;
       this.orders = orders;
    }
   
    public Integer getIdorderStatus() {
        return this.idorderStatus;
    }
    
    public void setIdorderStatus(Integer idorderStatus) {
        this.idorderStatus = idorderStatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


