package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer idorder;
     private Customer customer;
     private OrderStatus orderStatus;
     private Date date;
     private Double total;
     private Double subtotal;
     private Double discount;
     private Double dueAmount;
     private Date deliverDate;
     private String description;
     private String uniqueIdentifierText;
     private Set invoices = new HashSet(0);
     private Set deliveries = new HashSet(0);
     private Set orderItems = new HashSet(0);
     private Set printingJobs = new HashSet(0);

    public Order() {
    }

	
    public Order(Customer customer, OrderStatus orderStatus, String uniqueIdentifierText) {
        this.customer = customer;
        this.orderStatus = orderStatus;
        this.uniqueIdentifierText = uniqueIdentifierText;
    }
    public Order(Customer customer, OrderStatus orderStatus, Date date, Double total, Double subtotal, Double discount, Double dueAmount, Date deliverDate, String description, String uniqueIdentifierText, Set invoices, Set deliveries, Set orderItems, Set printingJobs) {
       this.customer = customer;
       this.orderStatus = orderStatus;
       this.date = date;
       this.total = total;
       this.subtotal = subtotal;
       this.discount = discount;
       this.dueAmount = dueAmount;
       this.deliverDate = deliverDate;
       this.description = description;
       this.uniqueIdentifierText = uniqueIdentifierText;
       this.invoices = invoices;
       this.deliveries = deliveries;
       this.orderItems = orderItems;
       this.printingJobs = printingJobs;
    }
   
    public Integer getIdorder() {
        return this.idorder;
    }
    
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(Double dueAmount) {
        this.dueAmount = dueAmount;
    }
    public Date getDeliverDate() {
        return this.deliverDate;
    }
    
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUniqueIdentifierText() {
        return this.uniqueIdentifierText;
    }
    
    public void setUniqueIdentifierText(String uniqueIdentifierText) {
        this.uniqueIdentifierText = uniqueIdentifierText;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }
    public Set getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set orderItems) {
        this.orderItems = orderItems;
    }
    public Set getPrintingJobs() {
        return this.printingJobs;
    }
    
    public void setPrintingJobs(Set printingJobs) {
        this.printingJobs = printingJobs;
    }




}


