package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plate generated by hbm2java
 */
public class Plate  implements java.io.Serializable {


     private Integer idplate;
     private Customer customer;
     private String rackNumber;
     private Date date;
     private Integer plateCount;
     private String description;
     private Set plateHasPrintingJobs = new HashSet(0);

    public Plate() {
    }

	
    public Plate(Customer customer) {
        this.customer = customer;
    }
    public Plate(Customer customer, String rackNumber, Date date, Integer plateCount, String description, Set plateHasPrintingJobs) {
       this.customer = customer;
       this.rackNumber = rackNumber;
       this.date = date;
       this.plateCount = plateCount;
       this.description = description;
       this.plateHasPrintingJobs = plateHasPrintingJobs;
    }
   
    public Integer getIdplate() {
        return this.idplate;
    }
    
    public void setIdplate(Integer idplate) {
        this.idplate = idplate;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getRackNumber() {
        return this.rackNumber;
    }
    
    public void setRackNumber(String rackNumber) {
        this.rackNumber = rackNumber;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getPlateCount() {
        return this.plateCount;
    }
    
    public void setPlateCount(Integer plateCount) {
        this.plateCount = plateCount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPlateHasPrintingJobs() {
        return this.plateHasPrintingJobs;
    }
    
    public void setPlateHasPrintingJobs(Set plateHasPrintingJobs) {
        this.plateHasPrintingJobs = plateHasPrintingJobs;
    }




}


