package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1



/**
 * PlateHasPrintingJob generated by hbm2java
 */
public class PlateHasPrintingJob  implements java.io.Serializable {


     private Integer id;
     private Plate plate;
     private PrintingJob printingJob;

    public PlateHasPrintingJob() {
    }

    public PlateHasPrintingJob(Plate plate, PrintingJob printingJob) {
       this.plate = plate;
       this.printingJob = printingJob;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Plate getPlate() {
        return this.plate;
    }
    
    public void setPlate(Plate plate) {
        this.plate = plate;
    }
    public PrintingJob getPrintingJob() {
        return this.printingJob;
    }
    
    public void setPrintingJob(PrintingJob printingJob) {
        this.printingJob = printingJob;
    }




}


