package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PrintingJobStatus generated by hbm2java
 */
public class PrintingJobStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set printingJobs = new HashSet(0);

    public PrintingJobStatus() {
    }

	
    public PrintingJobStatus(String status) {
        this.status = status;
    }
    public PrintingJobStatus(String status, Set printingJobs) {
       this.status = status;
       this.printingJobs = printingJobs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPrintingJobs() {
        return this.printingJobs;
    }
    
    public void setPrintingJobs(Set printingJobs) {
        this.printingJobs = printingJobs;
    }




}


