package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RawItem generated by hbm2java
 */
public class RawItem  implements java.io.Serializable {


     private Integer idrawItem;
     private Brand brand;
     private String name;
     private String description;
     private Date date;
     private Set stocks = new HashSet(0);
     private Set grnItems = new HashSet(0);

    public RawItem() {
    }

    public RawItem(Brand brand, String name, String description, Date date, Set stocks, Set grnItems) {
       this.brand = brand;
       this.name = name;
       this.description = description;
       this.date = date;
       this.stocks = stocks;
       this.grnItems = grnItems;
    }
   
    public Integer getIdrawItem() {
        return this.idrawItem;
    }
    
    public void setIdrawItem(Integer idrawItem) {
        this.idrawItem = idrawItem;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }




}


