package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SellingItems generated by hbm2java
 */
public class SellingItems  implements java.io.Serializable {


     private Integer iditem;
     private String name;
     private Date date;
     private Double price;
     private Set orderItems = new HashSet(0);

    public SellingItems() {
    }

	
    public SellingItems(Date date) {
        this.date = date;
    }
    public SellingItems(String name, Date date, Double price, Set orderItems) {
       this.name = name;
       this.date = date;
       this.price = price;
       this.orderItems = orderItems;
    }
   
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Set getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set orderItems) {
        this.orderItems = orderItems;
    }




}


