package hibernate;
// Generated Apr 2, 2021 12:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idstock;
     private Grn grn;
     private RawItem rawItem;
     private String addedDate;
     private Integer qty;
     private Byte status;
     private Set stockHasStockOuts = new HashSet(0);

    public Stock() {
    }

	
    public Stock(Grn grn, RawItem rawItem) {
        this.grn = grn;
        this.rawItem = rawItem;
    }
    public Stock(Grn grn, RawItem rawItem, String addedDate, Integer qty, Byte status, Set stockHasStockOuts) {
       this.grn = grn;
       this.rawItem = rawItem;
       this.addedDate = addedDate;
       this.qty = qty;
       this.status = status;
       this.stockHasStockOuts = stockHasStockOuts;
    }
   
    public Integer getIdstock() {
        return this.idstock;
    }
    
    public void setIdstock(Integer idstock) {
        this.idstock = idstock;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public RawItem getRawItem() {
        return this.rawItem;
    }
    
    public void setRawItem(RawItem rawItem) {
        this.rawItem = rawItem;
    }
    public String getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(String addedDate) {
        this.addedDate = addedDate;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set getStockHasStockOuts() {
        return this.stockHasStockOuts;
    }
    
    public void setStockHasStockOuts(Set stockHasStockOuts) {
        this.stockHasStockOuts = stockHasStockOuts;
    }




}


