package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StockOut generated by hbm2java
 */
public class StockOut  implements java.io.Serializable {


     private Integer idstockOutTime;
     private Date date;
     private String description;
     private Set stockHasStockOuts = new HashSet(0);

    public StockOut() {
    }

    public StockOut(Date date, String description, Set stockHasStockOuts) {
       this.date = date;
       this.description = description;
       this.stockHasStockOuts = stockHasStockOuts;
    }
   
    public Integer getIdstockOutTime() {
        return this.idstockOutTime;
    }
    
    public void setIdstockOutTime(Integer idstockOutTime) {
        this.idstockOutTime = idstockOutTime;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getStockHasStockOuts() {
        return this.stockHasStockOuts;
    }
    
    public void setStockHasStockOuts(Set stockHasStockOuts) {
        this.stockHasStockOuts = stockHasStockOuts;
    }




}


