package hibernate;
// Generated Mar 31, 2021 6:04:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idsupplier;
     private String name;
     private String contact;
     private Set grns = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String name, String contact, Set grns) {
       this.name = name;
       this.contact = contact;
       this.grns = grns;
    }
   
    public Integer getIdsupplier() {
        return this.idsupplier;
    }
    
    public void setIdsupplier(Integer idsupplier) {
        this.idsupplier = idsupplier;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


